version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ehddls
      MYSQL_DATABASE: readly
      MYSQL_USER: ehddls
      MYSQL_PASSWORD: ehddls
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379

  backend:
    image: readly_backend
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod

    depends_on:
      - mysql
      - redis

  frontend:
    image: readly_frontend
    ports:
      - "3000:5173"

volumes:
  mysql-data:

##test build
##test build2
##testeststset
