spring:
  datasource:
    url: jdbc:mysql://localhost:3306/readly?serverTimezone=Asia/Seoul
    username: ssafy
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        format_sql: true
        # use_sql_comments: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
